languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Sobhan"
# description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[params]
  # mainSections = ["section1", "section2"]

[author]
   name = "Sobhan Mardan"
   image = "img/tall_me.jpg"
   headline = "Research Coordinator & Data Analyst"
   bio = "MSc. Kinesiology"
   links = [
    # { email = "mailto:sobhan09m@gmail.com" },
     #{ github = "https://github.com/SobzMD" },
     { linkedin = "https://www.linkedin.com/in/sobhan-mardan-5a6a7159/" },
    # { twitter = "https://twitter.com/SobhanMardan" }
     ]
