title: Sobhan Mardan Portfolio
baseURL: "https://sobhanmardan.netlify.app/"
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: Sobhan 
    weight: 1
  # fr:
  #   contentDir: content/fr
  #   title: Ananke Fr
  #   weight: 2
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  ananke_socials:
    - name: linkedin
      url: https://www.linkedin.com/in/sobhan-mardan-dezfouli-5a6a7159/
  author: ''
  background_color_class: bg-black
  description: Sobhan Mardan, MSc.
  favicon: ''
  recent_posts_number: 3
  site_logo: ''
  text_color: ''
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
